export const habits = [
  {
    id: "1",
    name: "Beber agua",
    category: "Salud",
    description: "Tomar al menos 8 vasos de agua al día para mantenerse hidratado y mejorar el metabolismo.",
    streak: 3,
    failures: 0,
    goal: 8,
    unit: "vasos",
    icon: "💧",
    color: "#3B82F6",
  },
  {
    id: "2",
    name: "Hacer ejercicio",
    category: "Fitness",
    description: "Realizar 30 minutos de actividad física moderada o intensa para fortalecer el cuerpo.",
    streak: 7,
    failures: 1,
    goal: 30,
    unit: "minutos",
    icon: "🏋️",
    color: "#10B981",
  },
  {
    id: "3",
    name: "Leer 20 minutos",
    category: "Mente",
    description: "Dedicar tiempo a la lectura para expandir conocimiento y relajar la mente antes de dormir.",
    streak: 1,
    failures: 3,
    goal: 20,
    unit: "minutos",
    icon: "📚",
    color: "#8B5CF6",
  },
  {
    id: "4",
    name: "Meditar",
    category: "Mente",
    description: "Practicar meditación o respiración consciente para reducir el estrés y mejorar el enfoque.",
    streak: 5,
    failures: 0,
    goal: 10,
    unit: "minutos",
    icon: "🧘",
    color: "#F59E0B",
  },
  {
    id: "5",
    name: "Dormir 8 horas",
    category: "Salud",
    description: "Mantener un horario de sueño regular para recuperar energía y consolidar la memoria.",
    streak: 2,
    failures: 2,
    goal: 8,
    unit: "horas",
    icon: "😴",
    color: "#6366F1",
  },
  {
    id: "6",
    name: "Comer frutas",
    category: "Nutrición",
    description: "Incluir al menos 3 porciones de fruta fresca en la dieta diaria para vitaminas esenciales.",
    streak: 10,
    failures: 0,
    goal: 3,
    unit: "porciones",
    icon: "🍎",
    color: "#EF4444",
  },
  {
    id: "7",
    name: "Caminar",
    category: "Fitness",
    description: "Dar al menos 7,000 pasos al día para mantenerse activo y mejorar la salud cardiovascular.",
    streak: 4,
    failures: 1,
    goal: 7000,
    unit: "pasos",
    icon: "🚶",
    color: "#14B8A6",
  },
  {
    id: "8",
    name: "Sin azúcar añadida",
    category: "Nutrición",
    description: "Evitar productos con azúcar añadida para mejorar la salud metabólica y reducir inflamación.",
    streak: 0,
    failures: 4,
    goal: 1,
    unit: "día completo",
    icon: "🚫",
    color: "#F97316",
  },
];

export const categories = ["Todas", "Salud", "Fitness", "Mente", "Nutrición"];

export const userProfile = {
  name: "Camilo",
  username: "@camilo859",
  joinedDate: "Enero 2025",
  goal: "Construir 5 hábitos sólidos este semestre",
};
